name: test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker compose build

      - name: Up only selected profile
        run: docker compose up -d --wait --wait-timeout 60

      - name: Run Tests
        run: |
          docker compose exec spark-connect-client python /app/tests/smoke/spark_iceberg.py

      - name: Logs on failure
        if: failure()
        run: docker compose logs --no-color

      - name: Down
        if: always()
        run: docker compose down -v
